name: SAE
channels:
  - nvidia
  - pytorch
  - defaults
dependencies:
  - python=3.10.16
  - pip:
      - torch==2.6.0
      - --extra-index-url https://download.pytorch.org/whl/cu118
      - torchvision==0.21.0
      - --extra-index-url https://download.pytorch.org/whl/cu118
      - torchaudio==2.6.0
      - --extra-index-url https://download.pytorch.org/whl/cu118
      - transformers==4.51.3
      - accelerate==1.6.0
      - jsonlines==4.0.0
      - openai==1.59.6
      - nnsight==0.4.3
      - pyvene==0.1.7
      - python-louvain==0.16