name: RoLM
channels:
  - nvidia
  - pytorch
  - defaults
dependencies:
  - python=3.9.21
  - pip:
      - torch==2.6.0
      - --extra-index-url https://download.pytorch.org/whl/cu118
      - transformers==4.47.0
      - accelerate==1.2.1
      - numpy==1.26.3
      - pandas==2.2.3
      - seaborn==0.13.2
      - scikit-learn==1.6.0
      - jsonlines==4.0.0
      - openai==1.59.6
      - nnsight==0.4.3
      - pyvene==0.1.7