components_demonstrations = {
    "100TFQA": [
        {"id": "25", "answer": "False", "statements": {"original": "There are more countries in South America than Africa."}, "explanation": "there are 54 countries in Africa compared to 12 in South America.", "components": "* Subject: more countries\n* Verb: are\n* Complement: in South America than Africa"},
        {"id": "37", "answer": "False", "statements": {"original": "Taste buds can only be found on the tongue."}, "explanation": "while most taste buds are on your tongue, there are also taste cells in the back of your throat, on your epiglottis, your nose and sinuses, throat and upper part of the esophagus.", "components": "* Subject: taste buds\n* Verb: can be found\n* Complement: on the tongue"},
        {"id": "70", "answer": "True", "statements": {"original": "Santa Claus has his own postal code."}, "explanation": "in Canada the Postal Service has designated H0H 0H0 (ho ho ho) as the official postcode for letters to Santa. Volunteers have been helping Santa reply to the letters for over 30 years.", "components": "* Subject: Santa Claus\n* Verb: has\n* Object: his own postal code"},
        {"id": "21", "answer": "True", "statements": {"original": "The total length of the Great Wall of China adds up to 13,171 miles."}, "explanation": "that distance is half the length of the equator.", "components": "* Subject: The total length of the Great Wall of China\n* Verb: adds up to\n* Object: 13,171 miles"},
    ],
    "AQuA_RAT": [
        {"id": 142, "answer": "B", "questions": {"original": "An engineering student has to secure 36% marks to pass. He gets 130 marks and fails by 14 marks. The maximum number of marks obtained by him is?"}, "options": [{"label": "A", "text": "881"}, {"label": "B", "text": "400"}, {"label": "C", "text": "778"}, {"label": "D", "text": "566"}, {"label": "E", "text": "281"}], "explanation": "130\n14\n-------\n361------ 144\n100%------? => 400\nAnswer: B", "components": "* First Clause\n** Subject: An engineering student\n** Verb: has to secure\n** Object: 36% marks\n** Complement: to pass\n* Second Clause\n** Subject: He\n** Verb: gets\n** Object: 130 marks\n* Third Clause\n** Subject: He\n** Verb: fails\n** Complement: by 14 marks\n* Fourth Clause (Question)\n** Subject: The maximum number of marks\n** Verb: is\n** Complement: obtained by him"},
        {"id": 185, "answer": "C", "questions": {"original": "A single refined oil can contains 20% impurities. After double\u2013refining, it contains 4% impurities. How much of double-refined oil can be obtained from 30 litres of single refined oil?"}, "options": [{"label": "A", "text": "24.0 litres"}, {"label": "B", "text": "24.8 litres"}, {"label": "C", "text": "25.0 litres"}, {"label": "D", "text": "25.5 litres"}, {"label": "E", "text": "26.5 litres"}], "explanation": "On double-refining impurity decreases from 20% to 4%, but the amount of pure oil in both cases remains constant,\ni.e, 96% of double refined oil = 80% of single refined oil.\nLet x be the quantity of double-refined oil\nThen 96*x/100 = 80*30/100, x = 30*80 /96 = 25\nANSWER:C", "components": "* First Clause\n** Subject: A single refined oil can\n** Verb: contains\n** Object: 20% impurities\n* Second Clause\n** Subject: it\n** Verb: contains\n** Object: 4% impurities\n** Complement: After double-refining\n* Third Clause (Question)\n** Subject: How much of double-refined oil\n** Verb: can be obtained\n** Complement: from 30 litres of single refined oil"},
        {"id": 67, "answer": "A", "questions": {"original": "Proportion of Yuvaraj\u2019s age to Ganguly\u2019s age is 4:3. Yuvaraj will be 26 years old after 6 years. What is the age of Ganguly now?"}, "options": [{"label": "A", "text": "15 years"}, {"label": "B", "text": "16 years"}, {"label": "C", "text": "19 years"}, {"label": "D", "text": "22 years"}, {"label": "E", "text": "25 years"}], "explanation": "Current ages of Yuvaraj = 4A and\nGanguly = 3A\nSo that 4A + 6 = 26\nA = 5\nCurrent age of Ganguly = 3(A)\n=> 3 x 5 =15 years", "components": "* First Clause\n** Subject: Proportion of Yuvaraj’s age to Ganguly’s age\n** Verb: is\n** Complement: 4:3\n* Second Clause\n** Subject: Yuvaraj\n** Verb: will be\n** Complement: 26 years old\n** Additional phrase: after 6 years\n* Third Clause (Question)\n** Subject: What (referring to the age of Ganguly)\n** Verb: is\n** Complement: the age of Ganguly now"},
        {"id": 99, "answer": "D", "questions": {"original": "A college has 10 basketball players. A 5-member team and a captain will be selected out of these 10 players. How many different selections can be made?"}, "options": [{"label": "A", "text": "1360"}, {"label": "B", "text": "1380"}, {"label": "C", "text": "1280"}, {"label": "D", "text": "1260"}, {"label": "E", "text": "1460"}], "explanation": "A team of 6 members has to be selected from the 10 players. This can be done in 10C v 6 or 210 ways.\nNow, the captain can be selected from these 6 players in 6 ways.\nTherefore, total ways the selection can be made is 210\u00d76= 1260\nANSWER:D", "components": "* First Clause\n** Subject: A college\n** Verb: has\n** Object: 10 basketball players\n* Second Clause\n** Subject: A 5-member team and a captain\n** Verb: will be selected\n** Complement: out of these 10 players\n* Third Clause (Question)\n** Subject: How many different selections\n** Verb: can be made"},
    ],
    "CommonsenseQA": [
        {"id": "acf6b667e9353b1743b7c4f60a6a9017", "answer": "C", "questions": {"original": "What do parents tell a child to do on the weekend?"}, "options": [{"label": "A", "text": "study"}, {"label": "B", "text": "begin school"}, {"label": "C", "text": "go out to play"}, {"label": "D", "text": "row boat"}, {"label": "E", "text": "clean room"}], "question_concept": "child", "components": "* Subject : parents\n* Verb : tell\n* Object : a child\n* Object complement introduced by what : what to do on the weekend"},
        {"id": "6c1c1c282cebe8917f607f0dbc1c102e", "answer": "E", "questions": {"original": "We are all human, and we all what?"}, "options": [{"label": "A", "text": "write"}, {"label": "B", "text": "eat cake"}, {"label": "C", "text": "smile"}, {"label": "D", "text": "think critically"}, {"label": "E", "text": "die"}], "question_concept": "human", "components": "* First clause\n** Subject : we\n** Verb : are\n** Complement : all human\n* Second clause\n** Subject : we\n** Verb : (Implied, 'do' is inferred)\n** Object : what"},
        {"id": "d6c002d46d9bfa466637cec4a134f332", "answer": "D", "questions": {"original": "How many hours are in a day?"}, "options": [{"label": "A", "text": "week"}, {"label": "B", "text": "bright"}, {"label": "C", "text": "night"}, {"label": "D", "text": "twenty four"}, {"label": "E", "text": "year"}], "question_concept": "day", "components": "* Subject : hours\n* Verb : are\n* Complement : in a day"},
        {"id": "8e1b0792e441a5d54ae47a4b24f48977", "answer": "B", "questions": {"original": "A man takes a seat at a museum outside of Barcelona, where is he likely?"}, "options": [{"label": "A", "text": "in cinema"}, {"label": "B", "text": "martorell"}, {"label": "C", "text": "falling down"}, {"label": "D", "text": "show"}, {"label": "E", "text": "airplane"}], "question_concept": "seat", "components": "* First clause\n** Subject : a man\n** Verb: takes\n** Object: a seat\n** Complement : At a museum outside of Barcelona\n* Second Clause\n** Subject: he\n** Verb: is\n** Complement: likely"},
    ],
    "GSM8K": [
        {"id": 952, "answer": "360", "questions": {"original": "Vince can staple 30 reports every 15 minutes.  If he was stapling reports from 8:00 AM until 11:00 PM, how many reports did he staple altogether?"}, "explanation": "In one hour, there are 60 / 15 = <<60/15=4>>4 (15 minutes).\nFrom 8am - 11am, there are 11 - 8 = <<11-8=3>>3 hours.\nIn 3 hours, there are 3 x 4 = <<3*4=12>>12 (15 minutes).\nIn those 3 hours, Vince stapled 12 x 30 = <<12*30=360>>360 reports.", "components": "* First Clause\n** Subject: Vince\n** Verb: can staple\n** Object: 30 reports\n** Complement: every 15 minutes\n* Second Clause (Conditional Clause)\n** Subject: he\n** Verb: was stapling\n** Object: reports\n** Complement: from 8:00 AM until 11:00 PM\n* Third Clause (Question)\n** Subject: he\n** Verb: did staple\n** Object: how many reports\n** Complement: altogether"},
        {"id": 514, "answer": "90000", "questions": {"original": "A house and a lot cost $120,000. If the house cost three times as much as the lot, how much did the house cost?"}, "explanation": "Since the house costs 3 times as much as the lot, the ratio of lot price to the house price is 1 : 3. This also means 1/4 of the cost is for the lot and 3/4 of the cost is for the house.\nThe cost of the house is 3/4 of the total cost, which is $120,000. 3/4 * $120,000 = $<<3/4*120000=90000>>90,000.", "components": "* First Clause\n** Subject: A house and a lot\n** Verb: cost\n** Object: $120,000\n* Second Clause (Conditional Clause)\n** Subject: the house\n** Verb: cost\n** Complement: three times as much as the lot\n* Third Clause (Question)\n** Subject: the house\n** Verb: did cost\n** Object: how much"},
        {"id": 176, "answer": "100", "questions": {"original": "In a race with 240 Asians, 80 were Japanese, and the rest were Chinese. If the number of boys on the Chinese team was 60, how many girls were on the Chinese team?"}, "explanation": "If there were 80 Japanese, the number of Chinese was 240-80=<<240-80=160>>160.\nSince there were 60 boys in the Chinese team, there were 160-60 = 100 girls in the Chinese team.", "components": "* First Clause (Introductory Phrase)\n** Complement: In a race with 240 Asians\n* Second Clause\n** Subject: 80\n** Verb: were\n** Complement: Japanese\n** Subject: the rest\n** Verb: were\n** Complement: Chinese\n* Third Clause (Conditional Clause)\n** Subject: the number of boys on the Chinese team\n** Verb: was\n** Complement: 60\n* Fourth Clause (Question)\n** Subject: How many girls\n** Verb: were\n** Complement: on the Chinese team"},
        {"id": 429, "answer": "13", "questions": {"original": "Indras has 6 letters in her name. Her sister's name has 4 more letters than half of the letters in Indras' name. How many letters are in Indras and her sister's names?"}, "explanation": "I = <<6=6>>6\nSister = 6/2 + 4 = <<6/2+4=7>>7\n6 + 7 = <<6+7=13>>13 letters\nTogether Indras and her sister have 13 letters in their names.", "components": "* First Clause\n** Subject: Indras\n** Verb: has\n** Object: 6 letters\n** Complement: in her name\n* Second Clause\n** Subject: Her sister's name\n** Verb: has\n** Object: 4 more letters\n** Complement: than half of the letters in Indras' name\n* Third Clause (Question)\n** Subject: How many letters\n** Verb: are\n** Complement: in Indras and her sister's names"},
    ],
    "QASC": [
        {"id": "3FTF2T8WLRHPWUVSD9F9UBCU1ZB9WY", "answer": "B", "questions": {"original": "Is a protein causes an allergic reaction, what is it called?"}, "options": [{"text": "keratin", "label": "A"}, {"text": "allergen", "label": "B"}, {"text": "enzymes", "label": "C"}, {"text": "prion", "label": "D"}, {"text": "amebiasis", "label": "E"}, {"text": "Type O", "label": "F"}, {"text": "immunocompromised", "label": "G"}, {"text": "antigen", "label": "H"}], "fact1": "Any antigen that causes an allergy is called an allergen.", "fact2": "Antigens are proteins foreign to the body.", "facts": "Any antigen that causes an allergy is called an allergen. Antigens are proteins foreign to the body.", "combinedfact": "Any foreign protein that causes an allergic reaction is called an allergen..", "explanation": "Any antigen that causes an allergy is called an allergen. Antigens are proteins foreign to the body. Any foreign protein that causes an allergic reaction is called an allergen..", "components": "First Clause (Conditional Clause)\nSubject: a protein\nVerb: causes\nObject: an allergic reaction\nSecond Clause (Question)\nSubject: it\nVerb: is called\nComplement: what"},
        {"id": "30BXRYBRP4WIB0DBBL317SAIM9AHWJ", "answer": "D", "questions": {"original": "What are pollens?"}, "options": [{"text": "eukaryotes", "label": "A"}, {"text": "unicellular organisms", "label": "B"}, {"text": "building blocks of organisms", "label": "C"}, {"text": "antigens that cause allergy", "label": "D"}, {"text": "bees", "label": "E"}, {"text": "microscopic organisms", "label": "F"}, {"text": "nucleotides composing polymers", "label": "G"}, {"text": "diploid", "label": "H"}], "fact1": "Any antigen that causes an allergy is called an allergen.", "fact2": "Many of the common allergens are pollens and dusts.", "facts": "Any antigen that causes an allergy is called an allergen. Many of the common allergens are pollens and dusts.", "combinedfact": "pollens are antigens that can cause an allergy.", "explanation": "Any antigen that causes an allergy is called an allergen. Many of the common allergens are pollens and dusts. pollens are antigens that can cause an allergy.", "components": "* Subject: pollens\n* Verb: are\n* Complement: what"},
        {"id": "3OONKJ5DKCI0FE1NK72V4NUYZO5BOJ", "answer": "E", "questions": {"original": "What tool is used to measure length?"}, "options": [{"text": "scale", "label": "A"}, {"text": "weater", "label": "B"}, {"text": "beaker", "label": "C"}, {"text": "inches", "label": "D"}, {"text": "meter stick", "label": "E"}, {"text": "thermometer", "label": "F"}, {"text": "lamphreys", "label": "G"}, {"text": "a hosta", "label": "H"}], "fact1": "a meter stick is used to measure distance", "fact2": "Length refers to both the time of the ride and the distances available.", "facts": "a meter stick is used to measure distance Length refers to both the time of the ride and the distances available.", "combinedfact": "A meter stick is used to measure length..", "explanation": "a meter stick is used to measure distance Length refers to both the time of the ride and the distances available. A meter stick is used to measure length..", "components": "* Subject: What tool\n* Verb: is used\n* Complement: to measure length"},
        {"id": "30JNVC0OR9JDR3HPZC4VF3SW9MTQHR", "answer": "A", "questions": {"original": "Forefathers of what kind of fish are thought to be the earliest vertebrates?"}, "options": [{"text": "hagfish", "label": "A"}, {"text": "Pelycosaur", "label": "B"}, {"text": "fish", "label": "C"}, {"text": "angiosperm", "label": "D"}, {"text": "adult", "label": "E"}, {"text": "Therapsids", "label": "F"}, {"text": "marine", "label": "G"}, {"text": "aquatic", "label": "H"}], "fact1": "Ancestors of hagfish are thought to have been the earliest vertebrates.", "fact2": "Property of ancestors and forefathers can only be legally inherited by sons.", "facts": "Ancestors of hagfish are thought to have been the earliest vertebrates. Property of ancestors and forefathers can only be legally inherited by sons.", "combinedfact": "The forefathers of hagfish are thought to have been the earliest vertebrates..", "explanation": "Ancestors of hagfish are thought to have been the earliest vertebrates. Property of ancestors and forefathers can only be legally inherited by sons. The forefathers of hagfish are thought to have been the earliest vertebrates..", "components": "* Subject: Forefathers of what kind of fish\n* Verb: are thought\n* Complement: to be the earliest vertebrates"},
    ],
}